# Generated by Django 4.2.3 on 2023-07-22 01:44

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=50)),
                ("resumo", models.TextField(max_length=200)),
                ("conteudo", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "imagem_post",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("imagens_de", models.CharField(max_length=50)),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Publicado em"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="main_app.categoria",
                    ),
                ),
            ],
        ),
    ]
